name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENV_FILE_S3_URL: s3://manually-created-bucket-s3o/env-files/cdktf-shared-infra.env
      USER_NAME: ${{ github.event.repository.owner.login }}
      GITHUB_IAM_ROLE_ARN: arn:aws:iam::542773719222:role/github_actions_role
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform

      - name: Install cdktf
        run: npm install -g cdktf-cli@latest

      - name: Set up aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.GITHUB_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy .env file
        run: aws s3 cp ${{ env.ENV_FILE_S3_URL }} .

      - name: Run npm install
        run: npm i

      - name: Run cdktf get
        run: cdktf get

      - name: Run jest
        run: npm run test

      - name: Run eslint
        run: npm run lint

      - name: Run cdktf deploy
        run: cdktf deploy --auto-approve
